apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  storageClassName: ""
  volumeName: ur-monitor-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
